create table if not exists users (
    id integer generated by default as identity primary key not null,
    name varchar(255) not null,
    email varchar(512) not null,
    constraint uq_user_email unique (email)
);

create table if not exists items (
    id integer generated by default as identity primary key not null,
    name varchar(255) not null,
    description varchar not null,
    available boolean not null,
    user_id integer references users (id) on delete cascade not null
);

create table if not exists bookings (
    id integer generated by default as identity primary key not null,
    item_id integer references items (id) on delete cascade,
    booker_id integer references users (id) on delete cascade,
    status varchar,
    start_booking timestamp without time zone,
    end_booking timestamp without time zone
);

create table if not exists comments (
    id integer generated by default as identity primary key not null,
    text varchar,
    item_id integer references items (id) on delete cascade,
    author_id integer references users (id) on delete cascade,
    created timestamp with time zone
);